[package]
name = "rakuten-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
maplit = "1.0.2"
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.12.0"
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["full"] }
